server:
  port: 8080

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/high_concurrence?useSSL=false
        username: root
        password: root
        
    datasource-slave:
        url: jdbc:mysql://127.0.0.1:3306/high_concurrence_slave?useSSL=false
        username: root
        password: root




